config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  Vitrage.routes(self, controller: 'vitrage_pieces')
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/projects/edit/:slug' => 'projects#edit', as: :edit_project
  get '/pages/edit/:slug' => 'pages#edit', as: :edit_page
  namespace :api, defaults: { format: 'json' } do
    get 'get_good_info/:slug', to: 'goods#show'
    get 'get_sliders', to: 'sliders#index'
    get 'get_small_home_series', to: 'series#get_small_home_series'
    get 'get_big_home_series', to: 'series#get_big_home_series'
    get 'get_series_info/:slug', to: 'series#show'
    get 'get_catalog_items', to: 'catalog#index'
    get 'get_projects', to: 'projects#index'
    get 'get_project_info/:slug', to: 'projects#show'
    get 'get_project_series/:slug', to: 'projects#get_related_series'
    get 'get_series_projects/:slug', to: 'series#get_related_projects'
    get 'get_basket_info', to: 'baskets#show'
    post 'add_basket_good', to: 'baskets#add_basket_good'
    post 'remove_basket_good', to: 'baskets#remove_basket_good'
    post 'send_feedback_request', to: 'feedbacks#feedback_request'
    post 'create_order', to: 'orders#create'
    get 'get_page_info/:slug', to: 'pages#show'
    get 'get_contacts', to: 'main#get_contacts'
    get 'get_seo', to: 'main#get_seo'
    get 'get_project_seo/:slug', to: 'projects#get_project_seo'
    get 'get_page_seo/:slug', to: 'pages#get_seo'
    get 'get_instagram_media', to: 'main#get_instagram_media'
    get 'get_next_project/:slug', to: 'projects#get_next_project'
  end

  get '*page', to: 'static#index', constraints: -> (req) do
    !req.xhr? && req.format.html?
  end

  root 'static#index'
end

app/models/project.rb
class Project < ApplicationRecord
  has_one :main_slider, dependent: :destroy
  validates :title, :preview_image, :slug, :prior, presence: true
  validates :title, :slug, uniqueness: true
  mount_uploader :preview_image, ProjectImageUploader
  has_and_belongs_to_many :goods

  acts_as_vitrage_owner

  before_validation :prepare_slug

  scope :ordered, -> { order(prior: :asc, id: :desc) }
  scope :visibles, -> { where(hided: false) }

  def get_styled_title
    styled_title = []
    self.title.split(' ').each do |word|
      final_word = word
      self.get_related_series.pluck(:title).each do |series_title|
        if word.index(series_title)
          final_word = "<span class='accent-project-word'>#{word}</span>"
          break
        end
      end
      styled_title.push(final_word)
    end
    return styled_title.join(' ')
  end

  def get_related_series
    Series.joins(goods: [:goods_projects]).where(goods_projects: { project_id: self.id  }).distinct
  end

  def prepare_slug
    self.slug = UrlStringPreparator.slug(self.slug, self.title) unless self.slug.present?
  end

  def next
    if Project.visibles.count > 1
      Project.visibles.where("id > ?", id).order("id ASC").first || Project.visibles.first
    else
      nil
    end
  end
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController
  def index
    projects = Project.visibles.ordered
    data = []
    projects.each do |project|
      data.push( { title: project.get_styled_title, imageUrl: project.preview_image.catalog_thumb.url,
                 description: project.location_description, slug: project.slug} )
    end
    return render json: data
  end

  def show
    @project = Project.find_by(slug: params[:slug])
    data = render_to_string("projects/_show", :formats => [:html], :layout => false, :locals => {:project => @project})
    return render json: data
  end

  def get_related_series
    project = Project.find_by(slug: params[:slug])
    related_series = project.get_related_series.visibles.ordered
    data = []
    related_series.each do |series|
      data.push({title: series.title, imageUrl: series.preview_image.catalog_thumb.url, shortDescription: series.short_description,
                 group: series.group, model: "series", slug: series.slug})
    end
    return render json: data
  end

  def get_project_seo
    project = Project.find_by(slug: params[:slug])
    data = get_entity_seo(project)
    return render json: data
  end

  def get_next_project
    project = Project.find_by(slug: params[:slug])
    next_project = project.next ? { title: project.next.title, url: "/projects/#{project.next.slug}", linkTitle: "Следующий кейс" } : {}
    return render json: next_project
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_admin_user!, only: :edit

  def edit
    @project = Project.find_by(slug: params[:slug])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_show.html.slim
.container.grid-container.vtrg-header
  h1.h1-title.vtrg-title
    = @project.title
.container.vtrg-container
  = show_vitrage_for @project

app/views/projects/edit.html.slim
header.header.container.grid-container
  = link_to "/", class: "header__logo"
    svg width="189" height="53" viewBox="0 0 189 53" fill="none" xmlns="http://www.w3.org/2000/svg"
      path d="M56.1365 44.4318H9.02254V16.2109H0V45.619C0 50.0285 2.84922 52.8438 7.22481 52.8438H57.9003C62.3098 52.8438 65.1251 49.9946 65.1251 45.619V16.2109H56.1025V44.4318H56.1365Z" fill="currentColor"
      path d="M181.775 16.2109H129.811C125.401 16.2109 122.586 19.0602 122.586 23.4358V45.619C122.586 50.0285 125.435 52.8438 129.811 52.8438H181.775C186.185 52.8438 189 49.9946 189 45.619V23.4358C189 19.0262 186.151 16.2109 181.775 16.2109ZM179.977 44.4318H131.608V24.6229H179.977V44.4318Z" fill="currentColor"
      path d="M74.1816 23.4358V52.8438H83.2042V24.6229H92.2267V16.2109H81.4065C76.9969 16.2109 74.1816 19.0262 74.1816 23.4358Z" fill="currentColor"
      path d="M98.5371 7.22481V52.8463H107.56V24.6254H116.582V16.2134H107.56V8.44591H118.753V0H105.762C101.386 0 98.5371 2.84922 98.5371 7.22481Z" fill="currentColor"
  ul.header__tools
    li
      = link_to "В админку", edit_admin_project_path(@project.id), class: "admin-link btn"
    li
      = link_to "Просмотр", "/projects/#{(@project.slug)}", class: "admin-link btn"
= javascript_include_tag Ckeditor.cdn_url
.container.grid-container.vtrg-header
  h1.h1-title
    = @project.title
.container
  = edit_vitrage_for @project